# -*- coding: utf-8 -*-
"""Image2text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wq31ZrX0NrVYFTjuJNyWFYLjHvcMnuse
"""

import pytesseract
import cv2
import streamlit as st

def extract_text_from_image(image_path):
    # Read the image using OpenCV
    image = cv2.imread(image_path)

    # Convert the image to grayscale
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Use Tesseract to extract text
    extracted_text = pytesseract.image_to_string(gray_image)

    return extracted_text

def main():
    st.title("Form Information Display")

    # Upload image
    uploaded_file = st.file_uploader("Choose an image file", type=["png", "jpg", "jpeg"])

    if uploaded_file is not None:
        # Save the uploaded file temporarily
        with open("uploaded_form_image.png", "wb") as f:
            f.write(uploaded_file.getbuffer())

        # Extract text from the uploaded image
        form_text = extract_text_from_image("uploaded_form_image.png")

        st.header("Extracted Information")
        st.text(form_text)

if __name__ == "__main__":
    main()







